module.exports = Object.freeze({
    NAME_COLORS_DEFAULT : ['blue', 'green', 'red', 'darkviolet', 'cornflowerblue', 'crimson', 'seagreen', 'orangered'],
    NAME_COLORS_TERMINAL : ['aquamarine', 'khaki', 'palegreen', 'yellow', 'seagreen', 'darkorange', 'darkturquoise'],
    NAME_COLORS_BLUE : ['darkcyan', 'darkmagenta', 'royalblue', 'mediumvioletred', 'orchid'],
    LANGUAGES : {
    	'ASP.NET' : 'application/x-aspx',
    	'C' : 'text/x-csrc',
    	'C++' : 'text/x-c++src',
    	'C#' : 'text/x-csharp',
		'Clojure' : 'text/x-clojure',
		'COBOL' : 'text/x-cobol',
		'CoffeeScript' : 'text/x-coffeescript',
		'CSS' : 'text/css',
		'Django' : 'text/x-django',
		'EJS' : 'application/x-ejs',
		'Fortran' : 'text/x-Fortran',
		'Go' : 'text/x-go', 
		'Handlebars' : 'text/x-handlebars-template',
		'Haskell' : 'text/x-haskell',
		'HTML' : 'text/html',
		'Jade' : 'text/x-jade',
		'Java' : 'text/x-java',
		'Javascript' : 'text/javascript',
		'Markdown' : 'text/x-markdown',
		'MYSQL' : 'text/x-mysql',
		'Objective-C' : 'text/x-objectivec',
		'Pascal' : 'text/x-pascal',
		'Perl' : 'text/x-perl',
		'PHP' : 'text/x-php',
		'Python' : 'text/x-python',
		'R' : 'text/x-rsrc',
		'Ruby' : 'text/x-ruby',
		'Sass' : 'text/x-sass',
		'SCSS' : 'text/x-scss',
		'SQL' : 'text/x-sql',
		'Swift' : 'text/x-swift',
		'XML' : 'application/xml'
	}
});